Correcting the r01 file as per task

diff --git a/.github/workflows/r-01-creating_first_workflow.yml b/.github/workflows/r-01-creating_first_workflow.yml
--- a/.github/workflows/r-01-creating_first_workflow.yml
+++ b/.github/workflows/r-01-creating_first_workflow.yml
@@ -3,8 +3,18 @@ on:
     push
 
 jobs:
-    print_job:
+    echo-hello:
         runs-on: ubuntu-latest
         steps:
-            - name: this is first step
+            - name: Hello
               run: echo "Hello World"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: failing step
+              run: |
+                echo "I will fail"
+                exit 1
+            - name: say goodbye
+              run: echo "Good bye"
+    
